### ISSUE TITLE
Add support for bool data type

### ISSUE THREAD

**Issue by tokenfox** [ethstorage/web3url-gateway#11]
Reporting another issue that I cannot work around regarding lack of support for boolean data types

How to reproduce:

Find any ABI that uses bool. Example: `getTokenPRG(uint256, bool)` in 0x7d..d8 (PETARP):

    https://0x7d6433b77285cfdb2f91179f73588210fc53d3d8.w3eth.io/getTokenPRG/1/true

Produces error:

    400: Bad Request

    invalid domain name: true

I assume the problem is that type bool is not supported and there isn't really any workaround either.

In my opinion it would be good to get support for bool data types in parameters. Even if it would require explicit typing such as:

    https://0x7d6433b77285cfdb2f91179f73588210fc53d3d8.w3eth.io/getTokenPRG/1/true!bool

**Comment by qizhou** [comment]
Sounds to be a good feature.  @nand2 Do you think we should add this to the updated ERC-4804 - ERC-6860?

**Comment by nand2** [comment]
Definitely agree to add support for all the native non-struct types instead of only a few specific ones.

**Comment by nand2** [comment]
This is now done on ERC-6860, implemented in the JS/golang versions, we can close this :)

**Comment by qizhou** [comment]
@syntrust is working on this

**Comment by syntrust** [comment]
Please confirm the format is as `type!value` and the type part cannot be omitted in the case of bool.

w3link:

https://0x7d6433b77285cfdb2f91179f73588210fc53d3d8.1.w3link.io/getTokenPRG/1/bool!true?returns=(bytes)

w3eth:
https://0x7d6433b77285cfdb2f91179f73588210fc53d3d8.w3eth.io/getTokenPRG/1/bool!true?returns=(bytes)

**Comment by qizhou** [comment]
The standard uses explicit type, but I feel implicit type should be also supported.  What do you think @nand2 ?

**Comment by nand2** [comment]
Yes we could detect it implicitely, it does not conflict with the current 5 autodetected types. 
Let's add it as an implicit type?

**Comment by nand2** [comment]
Ok it's been added on ERC, golang/js version.
@qizhou Do you have experience on stuck auto-merge ERC edits? https://github.com/ethereum/ERCs/pull/197 won't auto merge, not sure why.

**Comment by syntrust** [comment]
Merged https://github.com/ethstorage/web3url-gateway/pull/19 and now https://0x7d6433b77285cfdb2f91179f73588210fc53d3d8.1.w3link.io/getTokenPRG/1/true?returns=(bytes) works
