### ISSUE TITLE
Broken links caused by ethclient upgrade

### ISSUE THREAD

**Issue by syntrust** [ethstorage/web3url-gateway#16]
Now web3url-gateway uses https://github.com/web3-protocol/web3protocol-go as web3:// engine. 

The package now use a up-to-date go-ethereum dependency, and they recently are now using "input" instead of "data" in the JSON-RPC call (apparently "data" was kind of supported but was not the standard). Cf https://github.com/ethereum/go-ethereum/pull/28078 As a consequence, several tests to blockchains ids 1666600000, 1666700000, 100001, 1088, 599, 84531 fails because their RPCs does not recognize "data".

We may need to consider the downgrade of go-ethereum for backward compatibility.

Broken links that were accessible using the old version gateway:

https://0xcf664087a5bb0237a0bad6742852ec6c8d69a27a.hmy-s0.w3link.io/name?returns=(string)

https://0xc2f21f8f573ab93477e23c4abb363e66ae11bac5.qkc-s0.w3link.io/greet?returns=(string)

**Comment by nand2** [comment]
And here is the backport of go-ethereum (a few months back) so that it uses "data" again, unbreaking these RPCs. (tests added back, all tests are passing)
https://github.com/ethstorage/web3url-gateway/pull/17

**Comment by syntrust** [comment]
https://github.com/ethstorage/web3url-gateway/pull/17 is deployed and the links are working now.
