### ISSUE TITLE
?returns= and array of arrays

### ISSUE THREAD

**Issue by nand2** [ethstorage/web3url-gateway#9]
Hi!

In auto mode, ``?returns=`` supports arrays, such as ``?returns=(uint256[])``
Question : I assume it supports arrays of arrays as well then, such as : ``?returns=(uint256[][])`` , is it correct?

Thanks

**Comment by qizhou** [comment]
That is correct according to my understanding of solidity ABI.

**Comment by nand2** [comment]
Great thanks, I will add it to the web3protocol lib (if not already working), and to the tests.
